import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';


import "./globals.css";
import CustomLayout from "@/components/CustomLayout";


const noto_sans = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next APP Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto_sans.className}>
      <AntdRegistry>
         <CustomLayout>{children}</CustomLayout>
      </AntdRegistry>
      </body>
    </html>
  );
}
